services:  
    backend:    
    build:      
      context: ./backend    
    ports:      
    - "3000:3000"    
    depends_on:      
      mysql:        
        condition: service_healthy

    frontend:       
      build:      
        context: ./frontend    
      ports:      
      - "80:80"    
      depends_on:      
      - backend

    mysql:    
      image: mysql:8.4    
      restart: always    
      environment:      
        MYSQL_ROOT_PASSWORD: password      
        MYSQL_DATABASE: test    
      ports:      
      - "3306:3306"    
      healthcheck:      
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]      
        timeout: 20s      
        retries: 10    
        volumes:      
        - mysql_data:/var/lib/mysql  

volumes:  
    mysql_data: